# Generated by Django 4.1.2 on 2022-10-25 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('number_of_emp', models.IntegerField()),
                ('number_of_room', models.IntegerField()),
                ('number_of_clients', models.IntegerField()),
                ('company_name', models.CharField(max_length=200)),
                ('company_email', models.CharField(max_length=30)),
                ('Applied', models.BooleanField(default=False)),
                ('Denied', models.BooleanField(default=False)),
                ('Approved', models.BooleanField(default=False)),
                ('is_alloted', models.BooleanField(default=False)),
                ('alloted_slot', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
