# Generated by Django 4.1.2 on 2022-10-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='room_number',
            field=models.IntegerField(null=True),
        ),
    ]
