# Generated by Django 4.1.2 on 2022-10-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_slot_assigned_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Applied',
            field=models.BooleanField(default=True),
        ),
    ]
